/**
 * Platform-level game engine contract.
 *
 * Every game on the platform (Cabo now, more later) implements this
 * interface. Networking code talks ONLY to this interface — never to
 * game-specific rules.
 */

import type { Card } from './cards.js';

/** A participant inside a running game. */
export interface GamePlayer {
  /** Stable player id (platform-level, from the room). */
  id: string;
  name: string;
  /** Seat index — defines turn order. */
  seat: number;
}

/** Machine-readable game action sent by a client. */
export interface GameAction {
  type: string;
  playerId: string;
  /** Monotonic client timestamp (ms) used to order near-simultaneous actions. */
  clientTs?: number;
  payload?: unknown;
}

/** Structured, public-safe event appended to the game log. */
export interface GameEvent {
  seq: number;
  type: string;
  playerId?: string;
  timestamp: string;
  payload?: Record<string, unknown>;
}

/** Result of applying (or rejecting) an action. */
export interface ActionResult {
  ok: boolean;
  error?: string;
  /** Events generated by this action, in order. */
  events: GameEvent[];
}

/**
 * View of the game for one specific viewer. The engine is responsible for
 * filtering: hidden information must never appear in another player's view.
 */
export interface PlayerView {
  /** Opaque per-viewer sync token; changes whenever the view changes. */
  revision: number;
  phase: string;
  /** Seat-ordered summary of every player (public info only). */
  players: Array<{
    id: string;
    name: string;
    cardCount: number;
    isCurrentTurn: boolean;
  }>;
  /** Cards this viewer is allowed to see, keyed by card id. */
  knownCards: Record<string, Card>;
  /** Ids of cards in each player's hand, in position order (values hidden unless known). */
  handCardIds: Record<string, string[]>;
  /** Number of cards left in the deck. */
  deckCount: number;
  /** Top of discard pile — always public. Empty array when none. Oldest-first. */
  discardTop: Card | null;
  events: GameEvent[];
}

export interface GameEngine {
  /** Game type identifier, e.g. "cabo". */
  readonly gameId: string;
  /** Serialized state version — bump on breaking changes. */
  readonly stateVersion: number;

  createGame(players: GamePlayer[], options?: Record<string, unknown>): void;
  getPublicState(): unknown;
  getPlayerState(playerId: string): PlayerView;
  validateAction(action: GameAction): boolean;
  handleAction(action: GameAction): ActionResult;
  calculateScore(): Record<string, number>;
  isGameFinished(): boolean;
}
